# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(553, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 40, 248, 281))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_time = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 0, 0, 1, 1)
        self.label_amp = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_amp.setFont(font)
        self.label_amp.setObjectName("label_amp")
        self.gridLayout.addWidget(self.label_amp, 2, 0, 1, 1)
        self.spinBox_sampling_rate = QtWidgets.QSpinBox(self.widget)
        self.spinBox_sampling_rate.setMinimum(1)
        self.spinBox_sampling_rate.setMaximum(1000000)
        self.spinBox_sampling_rate.setProperty("value", 1000)
        self.spinBox_sampling_rate.setObjectName("spinBox_sampling_rate")
        self.gridLayout.addWidget(self.spinBox_sampling_rate, 1, 1, 1, 1)
        self.doubleSpinBox_freq = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_freq.setDecimals(3)
        self.doubleSpinBox_freq.setMinimum(0.001)
        self.doubleSpinBox_freq.setMaximum(1000000.0)
        self.doubleSpinBox_freq.setSingleStep(0.1)
        self.doubleSpinBox_freq.setProperty("value", 2.0)
        self.doubleSpinBox_freq.setObjectName("doubleSpinBox_freq")
        self.gridLayout.addWidget(self.doubleSpinBox_freq, 3, 1, 1, 1)
        self.doubleSpinBox_end_time = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_end_time.setDecimals(3)
        self.doubleSpinBox_end_time.setMinimum(0.001)
        self.doubleSpinBox_end_time.setMaximum(1000000.0)
        self.doubleSpinBox_end_time.setProperty("value", 10.0)
        self.doubleSpinBox_end_time.setObjectName("doubleSpinBox_end_time")
        self.gridLayout.addWidget(self.doubleSpinBox_end_time, 0, 1, 1, 1)
        self.doubleSpinBox_amp = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_amp.setDecimals(3)
        self.doubleSpinBox_amp.setMinimum(0.001)
        self.doubleSpinBox_amp.setMaximum(1000000.0)
        self.doubleSpinBox_amp.setProperty("value", 1.0)
        self.doubleSpinBox_amp.setObjectName("doubleSpinBox_amp")
        self.gridLayout.addWidget(self.doubleSpinBox_amp, 2, 1, 1, 1)
        self.label_sampling_rate = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_sampling_rate.setFont(font)
        self.label_sampling_rate.setObjectName("label_sampling_rate")
        self.gridLayout.addWidget(self.label_sampling_rate, 1, 0, 1, 1)
        self.label_freq = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_freq.setFont(font)
        self.label_freq.setObjectName("label_freq")
        self.gridLayout.addWidget(self.label_freq, 3, 0, 1, 1)
        self.pushButton_plot_signal = QtWidgets.QPushButton(self.widget)
        self.pushButton_plot_signal.setObjectName("pushButton_plot_signal")
        self.gridLayout.addWidget(self.pushButton_plot_signal, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.label_noise_amp = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_noise_amp.setFont(font)
        self.label_noise_amp.setObjectName("label_noise_amp")
        self.gridLayout.addWidget(self.label_noise_amp, 6, 0, 1, 1)
        self.checkBox_add_noise = QtWidgets.QCheckBox(self.widget)
        self.checkBox_add_noise.setChecked(False)
        self.checkBox_add_noise.setTristate(False)
        self.checkBox_add_noise.setObjectName("checkBox_add_noise")
        self.gridLayout.addWidget(self.checkBox_add_noise, 5, 0, 1, 1)
        self.label_noise_deviation = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_noise_deviation.setFont(font)
        self.label_noise_deviation.setObjectName("label_noise_deviation")
        self.gridLayout.addWidget(self.label_noise_deviation, 7, 0, 1, 1)
        self.doubleSpinBox_noise_amp = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_noise_amp.setDecimals(3)
        self.doubleSpinBox_noise_amp.setMinimum(0.001)
        self.doubleSpinBox_noise_amp.setMaximum(1000000.0)
        self.doubleSpinBox_noise_amp.setProperty("value", 0.2)
        self.doubleSpinBox_noise_amp.setObjectName("doubleSpinBox_noise_amp")
        self.gridLayout.addWidget(self.doubleSpinBox_noise_amp, 6, 1, 1, 1)
        self.doubleSpinBox_noise_deviation = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_noise_deviation.setDecimals(3)
        self.doubleSpinBox_noise_deviation.setMinimum(0.001)
        self.doubleSpinBox_noise_deviation.setMaximum(1000000.0)
        self.doubleSpinBox_noise_deviation.setProperty("value", 0.1)
        self.doubleSpinBox_noise_deviation.setObjectName("doubleSpinBox_noise_deviation")
        self.gridLayout.addWidget(self.doubleSpinBox_noise_deviation, 7, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 553, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_time.setText(_translate("MainWindow", "End time [s]"))
        self.label_amp.setText(_translate("MainWindow", "Amplitude [mm]"))
        self.label_sampling_rate.setText(_translate("MainWindow", "Sampling rate [Hz]"))
        self.label_freq.setText(_translate("MainWindow", "Frequency [Hz]"))
        self.pushButton_plot_signal.setText(_translate("MainWindow", "Generate and plot signal"))
        self.label_noise_amp.setText(_translate("MainWindow", "Noise amplitude [mm]"))
        self.checkBox_add_noise.setText(_translate("MainWindow", "Add noise"))
        self.label_noise_deviation.setText(_translate("MainWindow", "std deviation [-]"))

